# Generated by Django 3.1.5 on 2021-01-18 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invNumber', models.CharField(max_length=20)),
                ('invDate', models.CharField(max_length=20)),
                ('buyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.buyerdetails')),
            ],
        ),
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Adress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productDescription', models.CharField(max_length=100)),
                ('unit_price', models.FloatField()),
                ('qnty', models.IntegerField()),
                ('tax_amount', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('invId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='sellerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.sellerdetails'),
        ),
    ]
